spring:
    application:
            name: base-project
    profiles:
        active: dev
    thymeleaf:
            mode: HTML5
            cache: false
    jpa:
            database: MYSQL
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
            hibernate:
                ddl-auto: none
                naming:
                    implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            open-in-view: false
            show-sql: true
            properties:
                #主键生成策略
                hibernate.id.new_generator_mappings: true
                #二级缓存 默认为true
                hibernate.cache.use_second_level_cache: false
                #缓存
                hibernate.cache.use_query_cache: false
                #统计信息
                hibernate.generate_statistics: true
                #sql格式化
                hibernate.format_sql: true

server:
    port: 8001
    #接口前缀
    context-path: /base

security:
    basic:
        enabled: false


logging:
    level:
        com.xxl.job.executor.service.info: info
        com.zoro: info
    path: /data/logs/${spring.application.name}