spring:
    profiles:
        active: dev
        include: swagger
    jackson:
        serialization.indent_output: true
    datasource:
        # 多数据源  主要数据库
        primary:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/base1?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
            username: root
            password:
            test-on-borrow: true
            validation-interval: 30
            validation-query: SELECT 1
            # 数据库连接池
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 50
                    prepStmtCacheSqlLimit: 1024
                    useServerPrepStmts: true
        secondary:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/base2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
            username: root
            password:
            test-on-borrow: true
            validation-interval: 30
            validation-query: SELECT 1
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 50
                    prepStmtCacheSqlLimit: 1024
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        pool:
            # 最大空闲数
            max-idle: 20
            min-idle: 10
            # 连接池最大数据库连接数（使用负值表示没有限制）
            max-active: 50
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1

application:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    security:
        authentication:
            jwt:
                secret: biubiubiu
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 295200
    cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
        exposed-headers: Authorization
        allow-credentials: true
        max-age: 1800
    httpclient:
        pool:
            max_total: 50
            max_per_route: 10
        standard:
            socket_timeout: 10000
            connect_timeout: 5000
        wld:
            socket_timeout: 10000
            connect_timeout: 5000